# -*- makefile -*-

build: kernel/kernel.bin
    
# run if source file changed
build/extendedProgram.bin: src/extendedProgram.S src/lib/*.S
	mkdir -p build && \
	nasm -fbin $< -o $@

build/bootloader.bin: src/bootloader.S src/lib/*.S
	mkdir -p build && \
	nasm -fbin $< -o $@

kernel/kernel.bin: build/bootloader.bin build/extendedProgram.bin
	mkdir -p kernel && \
	cat $^ > $@

qemu:
	qemu-system-x86_64 kernel/kernel.bin

clean:
	rm  */*.bin