# -*- makefile -*-

build: build/kernel.bin

run: qemu
    
# run if source file changed
build/bin/main.bin: src/main.S src/lib/*.S
	mkdir -p build && \
	mkdir -p build/bin && \
	nasm -fbin $< -o $@

build/bin/bootloader.bin: src/bootloader.S src/lib/*.S
	mkdir -p build && \
	mkdir -p build/bin && \
	nasm -fbin $< -o $@

build/kernel.bin: build/bin/bootloader.bin build/bin/main.bin
	cat $^ > $@

qemu:
	qemu-system-x86_64 build/kernel.bin

clean:
	rm  -rf build